---
output:
  pdf_document:
    fig_caption: yes
    includes:
      in_header: header.tex
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo = FALSE, results="verbatim", warning=FALSE)
library(dplyr)
library(readxl)
library(ggplot2)
```

\newpage
\tableofcontents
\newpage

# Récupération des données et séparation

```{r}
# Importation des données
# data <- read_excel("~/Documents/GitHub/UT4M_psycho/Glycémie/Donnée/Données_Glycémie/data_glucoseV1.xlsx")
data<- read_excel("data_glucoseV1.xlsx")


# Séparer les données en deux groupes pour chaque type de course
# data_100km <- data %>% filter(Course == "100 km")
# data_160km <- data %>% filter(Course == "160 km")

data_100km <- data %>% filter(course == "100 km")
data_160km <- data %>% filter(course == "160 km")
```

# Avant/Pendant/Après courses 

## Par date

```{r message=FALSE, warning=FALSE}
# Regrouper par jour, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_100km <- data_100km %>%
  group_by(day = as.Date(datetime), course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_100km, aes(x = day, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par jour pour tous les participants de la course 100 km",
       x = "Jour",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_date(date_labels = "%d/%m/%Y", date_breaks = "1 day") + # Format de l'axe des abscisses
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Inclinaison des étiquettes
  geom_vline(xintercept = as.Date("2023-07-22"), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.Date("2023-07-24"), linetype = "dashed", color = "red")+
  annotate("text", x = as.Date("2023-07-19"), y = max(grouped_data_100km$median_glucose) + 10, label = "Avant la course", vjust = 1, hjust = 1, color = "black") +
  annotate("text", x = as.Date("2023-07-23"), y = max(grouped_data_100km$median_glucose) + 12, label = "Pendant \n la \n course", vjust = 1, hjust = 0.5, color = "red") +
  annotate("text", x = as.Date("2023-07-25"), y = max(grouped_data_100km$median_glucose) + 10, label = "Après la course", vjust = 1, hjust = -0.5, color = "black")
```

```{r message=FALSE, warning=FALSE}
# Regrouper par jour, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_160km <- data_160km %>%
  group_by(day = as.Date(datetime), course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_160km, aes(x = day, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par jour pour tous les participants de la course 160 km",
       x = "Jour",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_date(date_labels = "%d/%m/%Y", date_breaks = "1 day") + # Format de l'axe des abscisses
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Inclinaison des étiquettes
  geom_vline(xintercept = as.Date("2023-07-21"), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.Date("2023-07-23"), linetype = "dashed", color = "red")+
  annotate("text", x = as.Date("2023-07-19"), y = max(grouped_data_160km$median_glucose) + 19, label = "Avant la course", vjust = 1, hjust = 1, color = "black") +
  annotate("text", x = as.Date("2023-07-22"), y = max(grouped_data_160km$median_glucose) + 21, label = "Pendant \n la \n course", vjust = 1, hjust = 0.5, color = "red") +
  annotate("text", x = as.Date("2023-07-24"), y = max(grouped_data_160km$median_glucose) + 19, label = "Après la course", vjust = 1, hjust = -0.5, color = "black")
```

## Par heure

```{r message=FALSE, warning=FALSE}
# Regrouper par date et heure, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_100km <- data_100km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:00:00")), course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_100km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par heure pour tous les participants de la course 100 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 day") + # Format de l'axe des abscisses (on ne peut pas mettre par heure car ilisible)
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Inclinaison des étiquettes
  geom_vline(xintercept = as.POSIXct("2023-07-22 07:00:00"), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct("2023-07-24 07:00:00"), linetype = "dashed", color = "red") +
  annotate("text", x = as.POSIXct("2023-07-19 07:00:00"), y = max(grouped_data_100km$median_glucose) + 10, label = "Avant la course", vjust = 1, hjust = 1, color = "black") +
  annotate("text", x = as.POSIXct("2023-07-23 07:00:00"), y = max(grouped_data_100km$median_glucose) + 12, label = "Pendant \n la \n course", vjust = 1, hjust = 0.5, color = "red") +
  annotate("text", x = as.POSIXct("2023-07-25 07:00:00"), y = max(grouped_data_100km$median_glucose) + 10, label = "Après la course", vjust = 1, hjust = -0.5, color = "black")
```

```{r}
# Regrouper par date et heure, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_160km <- data_160km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:00:00")), course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_160km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par heure pour tous les participants de la course 160 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 day") + # Format de l'axe des abscisses (on ne peut pas mettre par heure car ilisible)
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Inclinaison des étiquettes
  geom_vline(xintercept = as.POSIXct("2023-07-21 07:00:00"), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.POSIXct("2023-07-23 07:00:00"), linetype = "dashed", color = "red") +
  annotate("text", x = as.POSIXct("2023-07-19 07:00:00"), y = max(grouped_data_160km$median_glucose) + 10, label = "Avant la course", vjust = 1, hjust = 1, color = "black") +
  annotate("text", x = as.POSIXct("2023-07-22 07:00:00"), y = max(grouped_data_160km$median_glucose) + 12, label = "Pendant \n la \n course", vjust = 1, hjust = 0.5, color = "red") +
  annotate("text", x = as.POSIXct("2023-07-24 07:00:00"), y = max(grouped_data_160km$median_glucose) + 10, label = "Après la course", vjust = 1, hjust = -0.5, color = "black")
```

# Pendant la course

```{r message=FALSE, warning=FALSE}
# Filtrer les données pour la plage horaire spécifique
filtered_data_100km <- data_100km %>%
  filter(datetime >= as.POSIXct("2023-07-22 07:00:00") & datetime <= as.POSIXct("2023-07-24 07:00:00"))

# Regrouper par date et heure, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_100km <- filtered_data_100km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:00:00")), Course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_100km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par heure pour tous les participants pendant la course 100 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 hour") + # Afficher toutes les heures
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) # Inclinaison des étiquettes et taille du texte
```


```{r message=FALSE, warning=FALSE}
# Filtrer les données pour la plage horaire spécifique
filtered_data_100km <- data_100km %>%
  filter(datetime >= as.POSIXct("2023-07-22 07:00:00") & datetime <= as.POSIXct("2023-07-24 07:00:00"))

# Regrouper par date et heure, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_100km <- filtered_data_100km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:00:00")), Course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_100km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par heure pour tous les participants pendant la course 100 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 hour") + # Afficher toutes les heures
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) # Inclinaison des étiquettes et taille du texte
```


```{r}
# Filtrer les données pour la plage horaire spécifique
filtered_data_160km <- data_160km %>%
  filter(datetime >= as.POSIXct("2023-07-21 07:00:00") & datetime <= as.POSIXct("2023-07-23 07:00:00"))

# Regrouper par date et heure, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_160km <- filtered_data_160km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:00:00")), Course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_160km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par heure pour tous les participants pendant la course 160 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 hour") + # Afficher toutes les heures
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) # Inclinaison des étiquettes et taille du texte
```

## Par minutes

```{r}
# Filtrer les données pour la plage horaire spécifique
filtered_data_100km <- data_100km %>%
  filter(datetime >= as.POSIXct("2023-07-22 07:00:00") & datetime <= as.POSIXct("2023-07-24 07:00:00"))

# Regrouper par date, heure, minute, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_100km <- filtered_data_100km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:%M:00")), Course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_100km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par minutes pour tous les participants pendant la course 100 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 hour") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) # Inclinaison des étiquettes et taille du texte
```
```{r}
# Filtrer les données pour la plage horaire spécifique
filtered_data_160km <- data_160km %>%
  filter(datetime >= as.POSIXct("2023-07-21 07:00:00") & datetime <= as.POSIXct("2023-07-23 07:00:00"))

# Regrouper par date, heure, minute, course et calculer la médiane, le 1er et le 3e quantile du glucose
grouped_data_160km <- filtered_data_160km %>%
  group_by(datetime = as.POSIXct(format(datetime, "%Y-%m-%d %H:%M:00")), Course) %>%
  summarize(median_glucose = median(glucose),
            q1_glucose = quantile(glucose, 0.25),
            q3_glucose = quantile(glucose, 0.75))

# Tracer le graphique avec un axe des abscisses plus précis
ggplot(grouped_data_160km, aes(x = datetime, y = median_glucose)) +
  geom_line() +
  geom_ribbon(aes(ymin = q1_glucose, ymax = q3_glucose), alpha = 0.3, fill = "blue") +
  labs(title = "Médiane et quantiles du glucose par minutes pour tous les participants pendant la course 160 km",
       x = "Date et Heure",
       y = "Médiane du glucose") +
  theme_minimal() +
  scale_x_datetime(labels = scales::date_format("%d/%m/%Y %H:%M:%S"), breaks = "1 hour") + # Afficher toutes les 30 minutes
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) # Inclinaison des étiquettes et taille du texte

```

