---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="verbatim", warning=FALSE)
```

```{r packages, include=FALSE}
library(readxl)
library(dplyr)
library(gtsummary)
library(gt)
```

\newpage
\tableofcontents
\newpage

```{r}
data <- read_excel("../../Donnée/dataset_V6.xlsx")
```

```{r}
# Retrait des colonnes non nécessaires
data_analyse<- data%>%dplyr::select(!c(file_number,
                                       size,
                                       other_practice,
                                       other_practice_detail,
                                       diet,
                                       which_diet,
                                       which_drink_during_training,
                                       volume_drink_during_training,
                                       which_drink_during_competition,
                                       volume_drink_during_competition,
                                       which_eat_during_training,
                                       frequence_hours_eat_during_training,
                                       which_eat_during_competition,
                                       frequence_hours_eat_during_competition,
                                       other_trail_health_problem,
                                       trail_health_problem, 
                                       abandonment_point,
                                       scratch,
                                       Scratch_total,
                                       category,
                                       category_result,
                                       reason_medical_apointment_trail
))
```


```{r}
# Mise en forme des variables
data_analyse <- data_analyse %>% mutate_if(is.character, as.factor)

data_analyse$weekly_volume_profession <- ordered(data_analyse$weekly_volume_profession,
                                         levels = c("⩽ 35 heures / semaine" ,
                                                    "entre 36 et 45 heures / semaine",
                                                    "⩾ 45h / semaine" ))

data_analyse$start_trail <- ordered(data_analyse$start_trail, 
                            levels = c("< 2 ans" , "Entre 2 et 5 ans",
                                       "Entre 5 et 10 ans", "> 10 ans"))

data_analyse$time_proportion_other_practice <- ordered(data_analyse$time_proportion_other_practice, 
                                               levels = c("< 20%", "Entre 20% et 50%",
                                                          "> 50%"))

data_analyse$coach_for_trail <- ordered(data_analyse$coach_for_trail, 
                                levels = c("Oui", "Non"))

data_analyse$heart_rate_monitor_train <- ordered(data_analyse$heart_rate_monitor_train, 
                                         levels = c("Oui", "Non"))

data_analyse$heart_rate_monitor_competition <- ordered(data_analyse$heart_rate_monitor_competition, 
                                               levels = c("Oui", "Non"))

data_analyse$connected_platform <- ordered(data_analyse$connected_platform, 
                                   levels = c("Oui", "Non"))

data_analyse$ITRA_rating_know <- ordered(data_analyse$ITRA_rating_know, 
                                 levels = c("Oui", "Non"))

data_analyse$number_hours_practice_trail_phase_preparation = ordered(data_analyse$number_hours_practice_trail_phase_preparation,
                                                             levels=c('⩽ 3 heures / semaine',
                                                                      'Entre 3h et 7h / semaine',
                                                                      'Entre 7h et 12h / semaine',
                                                                      '> 12 heures / semaine'))

data_analyse$drop_practice_trail_phase_preparation = ordered(data_analyse$drop_practice_trail_phase_preparation,
                                                     levels=c('< 1000m / semaine',
                                                              'Entre 1000m et 2000m / semaine', 
                                                              '> 2000m / semaine'))

data_analyse$kilometres_practice_trail_phase_preparation = ordered(data_analyse$kilometres_practice_trail_phase_preparation,
                                                           levels=c('< 20km / semaine',
                                                                    'Entre 20km et 50km / semaine',
                                                                    'Entre 50km et 80km / semaine',
                                                                    '> 80km / semaine'))

data_analyse$number_hours_training_trail_phase_preparation = ordered(data_analyse$number_hours_training_trail_phase_preparation,
                                                             levels=c('⩽ 3 heures / semaine',
                                                                      'Entre 3h et 7h / semaine',
                                                                      'Entre 7h et 12h / semaine',
                                                                      '> 12 heures / semaine'))

data_analyse$trail_participation_last_two_seasons <- ordered(data_analyse$trail_participation_last_two_seasons, 
                                                     levels = c("Oui", "Non"))

data_analyse$distance_trail_participation_last_two_seasons=ordered(data_analyse$distance_trail_participation_last_two_seasons, levels=c("< 40km", "De 40km à 80km", "> 80km"))

data_analyse$frequence_trail_participation_last_two_seasons_by_season=ordered(data_analyse$frequence_trail_participation_last_two_seasons_by_season, 
                                                                              levels=c("1 à 3 courses / saison", 
                                                                               "4 à 8 courses / saison", 
                                                                               "> 8 courses / saison"))

data_analyse$which_races_UT4M_2023 <- ordered(data_analyse$which_races_UT4M_2023, 
                                      levels = c("Un des 20km", "Un des 40km",
                                                 "80km Challenge","100km Master",
                                                 "160km Xtrem / 160km Challenge"))

data_analyse$trail_injury_illness <- ordered(data_analyse$trail_injury_illness, 
                                     levels = c("Oui","Non"))

data_analyse$trail_health_problem_involve_no_training <- ordered(data_analyse$trail_health_problem_involve_no_training, 
                                                         levels = c("Oui","Non"))

data_analyse$time_trail_health_problem_involve_no_training <- ordered(data_analyse$time_trail_health_problem_involve_no_training, 
                                                              levels = c("< 2 semaines",
                                                                         "2 à 4 semaines",
                                                                         "5 à 8 semaines",
                                                                         "> 8 semaines"))

data_analyse$frequence_medical_apointment_trail <- ordered(data_analyse$frequence_medical_apointment_trail, 
                                                   levels = c("< 2x / an",
                                                              "2x à 6x / an",
                                                              "> 6x / an"))

data$smoke <- ordered(data$smoke, 
                      levels = c("Oui","Non"))

data_analyse <- as.data.frame(data_analyse)
```

## Résumé général des variables

```{r}
# Tableau général 
data_analyse%>% tbl_summary(missing_text = "(Données manquantes)",
                     label = list(sex ~ "Sexe",
                                  age ~ "Age",
                                  weight ~ "Poids",
                                  max_weight ~ "Poids maximal",
                                  min_weight ~ "Poids minimal",
                                  weekly_volume_profession ~ "Volume horaire consacré à la profession",
                                  start_trail ~ "Nombre d'années de pratique du trail",
                                  time_proportion_other_practice ~ "Proportion de temps accordée à la pratique d'autres sports",
                                  coach_for_trail ~ "Coach pour le trail",
                                  heart_rate_monitor_train ~ "Port d'un cardiofréquencemètre en entrainement",
                                  heart_rate_monitor_competition ~ "Port d'un cardiofréquencemètre en compétition",
                                  connected_platform ~ "Téléchargement des données sur une plateforme connectée",
                                  ITRA_rating ~ "Côte ITRA",
                                  ITRA_rating_know ~ "Connaissance de la côte ITRA",
                                  number_hours_practice_trail_phase_preparation ~ "Nombre d'heures d'entrainement en trail pour la préparation d'une course",
                                  drop_practice_trail_phase_preparation ~ "Dénivelé lors des entrainements en trail pour la préparation d'une course ",
                                  kilometres_practice_trail_phase_preparation ~ "Nombre de kilomètres parcourus pour l'entraînement en trail pour la préparation d'une course",
                                  number_hours_training_trail_phase_preparation ~ "Nombre d'heures d'entrainement pour la préparation d'une course",
                                  trail_participation_last_two_seasons ~ "Participation à une ou plusieurs courses de trail lors des 2 dernières saisons",
                                  distance_trail_participation_last_two_seasons ~ "Distance parcourue lors des dernières courses de trail", 
                                  frequence_trail_participation_last_two_seasons_by_season ~ "Nombre de courses de trail par saison",
                                  which_races_UT4M_2023 ~ "Course réalisée lors de l'UT4M 2023",
                                  trail_injury_illness ~ "Blessure ou maladie en lien avec la pratique du trail",
                                  trail_health_problem_involve_no_training ~ "Problèmes de santé ayant empêché l'entraînement",
                                  time_trail_health_problem_involve_no_training ~ "Durée d'impossibilité de s'entraîner",
                                  frequence_medical_apointment_trail ~ "Fréquence des rendez-vous médicaux",
                                  smoke ~ "Fumeur régulier",
                                  fulfillment ~ "Epanouissement",
                                  priority ~ "Priorités",
                                  intrinsic_motivation ~ "Motivation intrinsèque",
                                  identified_motivation ~ "Motivation identifiée",
                                  integrated_motivation ~ "Motivation intégrée",
                                  introjected_motivation ~ "Motivation introjectée",
                                  external_motivation ~ "Motivation externe",
                                  global_mental_force ~ "Force mentale globale",
                                  confidence ~ "Confiance",
                                  consistency ~ "Consistance",
                                  control ~ "Contrôle",
                                  general_internal_speech ~ "Discours interne",
                                  training_internal_speech ~ "Discours interne lors de l'entraînement",
                                  competition_internal_speech ~ "Discours interne lors de compétition",
                                  general_precompetitive_anxiety ~ "Anxiété pré-compétitive",
                                  somatic_anxiety ~ "Anxiété somatique",
                                  cognitive_anxiety ~ "Anxiété cognitive",
                                  harmonious_hobbies ~ "Passion harmonieuse",
                                  obsessive_hobbies ~ "Passion obsessive",
                                  addiction ~ "Addiction",
                                  do_not_finish ~ "Abandon"),
                     statistic = all_continuous() ~ "{mean} [{p25}, {p75}]",
                     missing = "no")%>%
  modify_header(label ~ "**Variable**")
```

## Analyse statistique des données par sexe

```{r}
data_analyse%>% tbl_summary(by = sex, missing_text = "(Données manquantes)",
                     label = list(age ~ "Age",
                                  weight ~ "Poids",
                                  max_weight ~ "Poids maximal",
                                  min_weight ~ "Poids minimal",
                                  weekly_volume_profession ~ "Volume horaire consacré à la profession",
                                  start_trail ~ "Nombre d'années de pratique du trail",
                                  time_proportion_other_practice ~ "Proportion de temps accordée à la pratique d'autres sports",
                                  coach_for_trail ~ "Coach pour le trail",
                                  heart_rate_monitor_train ~ "Port d'un cardiofréquencemètre en entrainement",
                                  heart_rate_monitor_competition ~ "Port d'un cardiofréquencemètre en compétition",
                                  connected_platform ~ "Téléchargement des données sur une plateforme connectée",
                                  ITRA_rating ~ "Côte ITRA",
                                  ITRA_rating_know ~ "Connaissance de la côte ITRA",
                                  number_hours_practice_trail_phase_preparation ~ "Nombre d'heures d'entrainement en trail pour la préparation d'une course",
                                  drop_practice_trail_phase_preparation ~ "Dénivelé lors des entrainements en trail pour la préparation d'une course ",
                                  kilometres_practice_trail_phase_preparation ~ "Nombre de kilomètres parcourus pour l'entraînement en trail pour la préparation d'une course",
                                  number_hours_training_trail_phase_preparation ~ "Nombre d'heures d'entrainement pour la préparation d'une course",
                                  trail_participation_last_two_seasons ~ "Participation à une ou plusieurs courses de trail lors des 2 dernières saisons",
                                  distance_trail_participation_last_two_seasons ~ "Distance parcourue lors des dernières courses de trail", 
                                  frequence_trail_participation_last_two_seasons_by_season ~ "Nombre de courses de trail par saison",
                                  which_races_UT4M_2023 ~ "Course réalisée lors de l'UT4M 2023",
                                  trail_injury_illness ~ "Blessure ou maladie en lien avec la pratique du trail",
                                  trail_health_problem_involve_no_training ~ "Problèmes de santé ayant empêché l'entraînement",
                                  time_trail_health_problem_involve_no_training ~ "Durée d'impossibilité de s'entraîner",
                                  frequence_medical_apointment_trail ~ "Fréquence des rendez-vous médicaux",
                                  smoke ~ "Fumeur régulier",
                                  fulfillment ~ "Epanouissement",
                                  priority ~ "Priorités",
                                  intrinsic_motivation ~ "Motivation intrinsèque",
                                  identified_motivation ~ "Motivation identifiée",
                                  integrated_motivation ~ "Motivation intégrée",
                                  introjected_motivation ~ "Motivation introjectée",
                                  external_motivation ~ "Motivation externe",
                                  global_mental_force ~ "Force mentale globale",
                                  confidence ~ "Confiance",
                                  consistency ~ "Consistance",
                                  control ~ "Contrôle",
                                  general_internal_speech ~ "Discours interne",
                                  training_internal_speech ~ "Discours interne lors de l'entraînement",
                                  competition_internal_speech ~ "Discours interne lors de compétition",
                                  general_precompetitive_anxiety ~ "Anxiété pré-compétitive",
                                  somatic_anxiety ~ "Anxiété somatique",
                                  cognitive_anxiety ~ "Anxiété cognitive",
                                  harmonious_hobbies ~ "Passion harmonieuse",
                                  obsessive_hobbies ~ "Passion obsessive",
                                  addiction ~ "Addiction",
                                  do_not_finish ~ "Abandon"),
                     statistic = all_continuous() ~ "{mean} [{p25}, {p75}]",
                     missing = "no")%>%
  modify_header(label ~ "**Variable**")%>%
  add_p()  %>%
  add_overall(col_label= "**Tous**, N = {N}")  %>%
  modify_header(label ~ "**Variable**", p.value = "**P-valeur**")
```


```{r}
# Pour les variables quantitatives
variables_numeriques <- names(data_analyse)[sapply(data_analyse, is.numeric)]
colonne_var <- c()
colonne_tous <- c()
colonne_homme <- c()
colonne_femme <- c()
colonne_pval <- c()

for(variable in variables_numeriques){
  moy_general <- mean(data_analyse[,variable], na.rm = TRUE)
  moy_homme <- mean(data_analyse[data_analyse$sex=="Homme",variable], na.rm = TRUE)
  moy_femme <- mean(data_analyse[data_analyse$sex=="Femme",variable], na.rm = TRUE)
  IC_general <- confint(lm(data_analyse[,variable] ~ 1), level = 0.95)
  IC_homme <- confint(lm(data_analyse[data_analyse$sex=="Homme",variable] ~ 1), level = 0.95)
  IC_femme <- confint(lm(data_analyse[data_analyse$sex=="Femme",variable] ~ 1), level = 0.95)
  p_valeur <- t.test(data_analyse[[variable]] ~ data_analyse$sex)$p.value
  colonne_var <- c(colonne_var,variable)
  colonne_tous <- c(colonne_tous,paste(round(moy_general,4), "[", round(IC_general[,1],2), ";", round(IC_general[,2],2), "]"))
  colonne_homme <- c(colonne_homme, paste(round(moy_homme,2), "[", round(IC_homme[,1],2), ";", round(IC_homme[,2],2), "]"))
  colonne_femme <- c(colonne_femme, paste(round(moy_femme,2), "[", round(IC_femme[,1],2), ";", round(IC_femme[,2],2), "]"))
  colonne_pval <- c(colonne_pval,round(p_valeur,4))
}

nom_colonnes <- c("Variable", "Tous, N = 358", paste("Homme, N = ", length(data_analyse[data_analyse$sex=="Homme",'age'])), paste("Femme, N = ", length(data_analyse[data_analyse$sex=="Femme",'age'])), "P-valeur")

extrait_tableau_numerique <- data.frame(colonne_var, colonne_tous, colonne_homme, colonne_femme, round(p.adjust(colonne_pval, method = "BH"),4))
colnames(extrait_tableau_numerique)<- c("colonne_var", "colonne_tous", "colonne_homme", "colonne_femme", "colonne_pval")
```

```{r}
# Pour les variables catégorielles
variables_categorielles <- names(data_analyse)[sapply(data_analyse, is.factor)]
colonne_var <- c()
colonne_tous <- c()
colonne_homme <- c()
colonne_femme <- c()
colonne_pval <- c()
extrait_tableau_categorielle = data.frame()
p_valeurs <- c()
j = 1

for(variable in variables_categorielles){
  p_valeurs = c(p_valeurs,prop.test(table(data_analyse[,variable], data_analyse$sex))$p.value)
}
p_valeurs <- round(p.adjust(p_valeurs, method = "BH"),4)

for(variable in variables_categorielles){
  nb_general = c()
  nb_femme = c()
  nb_homme = c()
  for (i in 1:dim(table(data_analyse[,variable], data_analyse[,'sex']))[1]){
    nb_general <- c(nb_general,table(data_analyse[,variable], data_analyse[,'sex'])[i,1] + table(data_analyse[,variable], data_analyse[,'sex'])[i,2])
    nb_femme <- c(nb_femme,table(data_analyse[,variable], data_analyse[,'sex'])[i,1])
    nb_homme <- c(nb_homme,table(data_analyse[,variable], data_analyse[,'sex'])[i,2])
    pourcent_homme <- nb_homme/nb_general*100
    pourcent_femme <- nb_femme/nb_general*100
  }
  p_valeur <- p_valeurs[j]
  colonne_var = c(variable, paste("     ",levels(data_analyse[,variable])))
  colonne_tous = c(" ", nb_general)
  colonne_homme = c(" ", paste(nb_homme, "(", round(pourcent_homme,0), "%)"))
  colonne_femme = c(" ", paste(nb_femme, "(", round(pourcent_femme,0), "%)"))
  colonne_pval = c(p_valeur, rep(" ", length(levels(data_analyse[, variable]))))
  df_new = data.frame(colonne_var, colonne_tous, colonne_homme, colonne_femme, colonne_pval)
  extrait_tableau_categorielle = rbind(extrait_tableau_categorielle,df_new)
  j = j + 1
}
```

```{r}
# Création du tableau final
nom_colonnes <- c("Variable", "Tous, N = 358", paste("Homme, N = ", length(data_analyse[data_analyse$sex=="Homme",'age'])), paste("Femme, N = ", length(data_analyse[data_analyse$sex=="Femme",'age'])), "P-valeur")

tableau_final = rbind(extrait_tableau_numerique, extrait_tableau_categorielle)
colnames(tableau_final)<- nom_colonnes
gt(tableau_final)
```


